config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
 
  
  resources :likes
  resources :searches

  resources :tags do
    resources :tag_aliases, param: :name, except: :show
  end

  resources :restaurants do
    resources :restaurant_locations
    resources :restaurant_aliases, param: :name, except: :show
  end 

  resources :users

  root 'tags#index'
  get '' => 'tags#search'
  post '' => 'tags#search'
  get '/tags/:id/tag_aliases/:name' => 'tags#show'
  get '/restaurants/:id/restaurant_aliases/:name' => 'restaurants#show'
  get '/views' => 'view#index'

end

app/controllers/tag_aliases_controller.rb
class TagAliasesController < ApplicationController
  respond_to :html

  def index
    @tag_aliases = TagAlias.where(tag_id: params[:tag_id])
    respond_with(@tag_aliases)
  end

  def show
        @tag_aliases = TagAlias.where(tag_id: params[:tag_id])

  end

  def new
    @tag_alias = TagAlias.new
  
  end

  def edit
  end

  def create
    @tag_alias = TagAlias.new(tag_alias_params)
    @tag_alias.save
    respond_with(@tag_alias.tag)
  end

  def update
    @tag_alias.update(tag_alias_params)
    respond_with(@tag_alias)
  end

  def destroy
    @tag_alias = TagAlias.where(tag_id: params[:tag_id], name: params[:name]).first
    @tag = @tag_alias.tag
    if @tag_alias.destroy
      redirect_to @tag
    end
  end

  private
    def set_tag_alias
      @tag_alias = TagAlias.find(params[:id])
    end

    def tag_alias_params
      params.require(:tag_alias).permit(:name, :tag_id)
    end
end

app/helpers/tag_aliases_helper.rb
module TagAliasesHelper
end

app/views/tag_aliases/_form.html.erb
<%= simple_form_for [@tag, @tag_alias], url: tag_tag_aliases_path do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.association :tag %>
  <%= f.button :submit %>
<% end %>

app/views/tag_aliases/edit.html.erb
<h1>Editing tag_alias</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_alias %> |
<%= link_to 'Back', tag_aliases_path %>

app/views/tag_aliases/index.html.erb
<h1>Listing tag_aliases</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_aliases.each do |tag_alias| %>
      <tr>
        <td><%= tag_alias.name %></td>
        <td><%= tag_alias.tag %></td>
        <td><%= link_to 'Show', tag_tag_aliases_url %></td>
        <td><%= link_to 'Destroy', [tag_alias.tag, tag_alias], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag alias', new_tag_tag_alias_path %>

app/views/tag_aliases/new.html.erb
<h1>New tag_alias</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_tag_aliases_path %>

app/views/tag_aliases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag_alias.name %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @tag_alias.tag %>
</p>

<%= link_to 'Edit', edit_tag_alias_path(@tag_alias) %> |
<%= link_to 'Back', tag_aliases_path %>