config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
 
  
  resources :likes
  resources :searches

  resources :tags do
    resources :tag_aliases, param: :name, except: :show
  end

  resources :restaurants do
    resources :restaurant_locations
    resources :restaurant_aliases, param: :name, except: :show
  end 

  resources :users

  root 'tags#index'
  get '' => 'tags#search'
  post '' => 'tags#search'
  get '/tags/:id/tag_aliases/:name' => 'tags#show'
  get '/restaurants/:id/restaurant_aliases/:name' => 'restaurants#show'
  get '/views' => 'view#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :likes, dependent: :destroy
	has_many :tag_aliases, dependent: :destroy
	has_many :restaurants, through: :likes

	validates :name, presence: true, uniqueness: { case_sensitive: false}
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  def search
    @tag = Tag.where('lower(name) = ?', params[:search][:tag_name].downcase).first
    if @tag.nil?
      @tag_alias = TagAlias.where(name: params[:search][:tag_name]).first
      @tag = @tag_alias.tag unless @tag_alias.nil?
      if @tag.nil?
        flash[:alert] = "Tag #{params[:search][:tag_name].titleize} doesn't exist!"
        redirect_to root_url
        return
      end
    end
    @restaurant_locations = RestaurantLocation.where('lower(city) = ?', params[:search][:city].downcase)
    @restaurants = []
    @restaurant_locations.each do |l|
      @restaurants << l.restaurant
    end
    if @restaurant_locations.empty?
      flash[:alert] = "No restaurants found in #{params[:search][:city].humanize}"
      redirect_to root_url
      return
    end
      @likes
  

 
    #@restaurants = @restaurants.distinct
    
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class = "jumbotron">

    <div class = "container-fluid">
      <h2> Tag pool: </h2>
      <% @tags.each do |tag| %>
      <a class="btn btn-primary" href = <%= tag_path(tag) %>> <%=tag.name.titleize%> <span class="badge"><%= tag.likes.size %></span> </a>
      <% end %>
      <div class = "row">
        <div class = "col-md-4 col-md-offset-3">
          <h2></h2>
      <a class = "btn btn-primary btn-lg btn-block" href = <%= new_tag_path %>> Add a new tag </a>
  </div>
</div>
</div>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/search.html.erb
<div class = "container">
	<h1>Found <%= pluralize(@restaurant_locations.size, 'restaurant') %>
		<% @restaurants.each do |l| %>
		<%= l.name %>
		<% end %>
		<%= @likes.size%>
</div>

app/views/tags/show.html.erb
<h1> <%= @tag.name %></h1>
<h2>Served in <%= pluralize(@tag.restaurants.distinct.size, 'restaurant') %> with <%= pluralize(@tag.likes.size, 'like')%>!</h2>
<div class = "row">
	<% @tag.restaurants.distinct.each do |restaurant| %>
	<div class = "col-md-4">
		<h3><%= link_to restaurant.name, restaurant %> </h3>
		<h4><%= pluralize(restaurant.likes.size, 'like')%></h4>
	</div>
	<% end %>
</div>

<div class = "row">
	    <div class = "container-fluid">
		      <h2> Tag aliases pool: <small>click on an alias to delete</small> </h2>
			      <% @tag.tag_aliases.each do |tag_alias| %>
			      	
			      		<div style="float: left; width: auto;">
			      			<p>
			     			
			     			 <%= button_to tag_alias.name.titleize, [tag_alias.tag, tag_alias], method: :delete, data: {confirm: 'Are you sure?'}, :class =>"btn btn-primary" %>
			     	 		</p>
			     	</div>
			     	
		      	  <% end %>

		</div>
</div>
<h2></h2>
<%= link_to 'New Tag alias', new_tag_tag_alias_path(@tag), :class =>"btn btn-primary" %>