config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
 
  
  resources :likes
  resources :searches

  resources :tags do
    resources :tag_aliases, param: :name, except: :show
  end

  resources :restaurants do
    resources :restaurant_locations
    resources :restaurant_aliases, param: :name, except: :show
  end 

  resources :users

  root 'tags#index'
  get '' => 'tags#search'
  post '' => 'tags#search'
  get '/tags/:id/tag_aliases/:name' => 'tags#show'
  get '/restaurants/:id/restaurant_aliases/:name' => 'restaurants#show'
  get '/views' => 'view#index'

end

app/models/restaurant_location.rb
class RestaurantLocation < ActiveRecord::Base
  belongs_to :restaurant

  validates :restaurant, presence: true
  validates :city, presence: true
end

app/controllers/restaurant_locations_controller.rb
class RestaurantLocationsController < ApplicationController
  before_action :set_restaurant_location, only: [:edit, :update, :destroy]

  # GET /restaurant_locations
  # GET /restaurant_locations.json
  def index
    @restaurant_locations = RestaurantLocation.all
  end

  # GET /restaurant_locations/1
  # GET /restaurant_locations/1.json
  def show
    @restaurant_locations = RestaurantLocation.where(restaurant_id: params[:restaurant_id])
  end

  # GET /restaurant_locations/new
  def new
    @restaurant_location = RestaurantLocation.new
  end

  # GET /restaurant_locations/1/edit
  def edit
  end

  # POST /restaurant_locations
  # POST /restaurant_locations.json
  def create
    @restaurant_location = RestaurantLocation.new(restaurant_location_params)

    respond_to do |format|
      if @restaurant_location.save
        format.html { redirect_to @restaurant_location.restaurant, notice: 'Restaurant location was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant_location }
      else
        format.html { render :new }
        format.json { render json: @restaurant_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurant_locations/1
  # PATCH/PUT /restaurant_locations/1.json
  def update
    respond_to do |format|
      if @restaurant_location.update(restaurant_location_params)
        format.html { redirect_to @restaurant_location, notice: 'Restaurant location was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant_location }
      else
        format.html { render :edit }
        format.json { render json: @restaurant_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant_locations/1
  # DELETE /restaurant_locations/1.json
  def destroy
    @restaurant_location.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_locations_url, notice: 'Restaurant location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant_location
      @restaurant_location = RestaurantLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_location_params
      params.require(:restaurant_location).permit(:address, :phone, :lat, :lng, :city, :restaurant_id)
    end
end

app/helpers/restaurant_locations_helper.rb
module RestaurantLocationsHelper
end

app/views/restaurant_locations/_form.html.erb
<%= simple_form_for [@restaurant, @restaurant_location], url: restaurant_restaurant_locations_path do |f| %>
  <%= f.error_notification %>
  <%= f.input :address %>
  <%= f.input :phone %>
  <%= f.input :city %>
  <%= f.association :restaurant %>
  <%= f.button :submit %>
<% end %>

app/views/restaurant_locations/edit.html.erb
<h1>Editing restaurant_location</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_location %> |
<%= link_to 'Back', restaurant_locations_path %>

app/views/restaurant_locations/index.html.erb
<h1>Listing restaurant_locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Phone</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>City</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant_locations.each do |restaurant_location| %>
      <tr>
        <td><%= restaurant_location.address %></td>
        <td><%= restaurant_location.phone %></td>
        <td><%= restaurant_location.lat %></td>
        <td><%= restaurant_location.lng %></td>
        <td><%= restaurant_location.city %></td>
        <td><%= restaurant_location.restaurant %></td>
        <td><%= link_to 'Show', restaurant_restaurant_locations_url %></td>
        <td><%= link_to 'Destroy', restaurant_restaurant_location_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant location', new_restaurant_location_path %>

app/views/restaurant_locations/new.html.erb
<h1>New restaurant_location</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_restaurant_locations_path %>

app/views/restaurant_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @restaurant_location.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant_location.phone %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @restaurant_location.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @restaurant_location.lng %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant_location.city %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @restaurant_location.restaurant %>
</p>

<%= link_to 'Edit', edit_restaurant_location_path(@restaurant_location) %> |
<%= link_to 'Back', restaurant_locations_path %>