config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
 
  
  resources :likes
  resources :searches

  resources :tags do
    resources :tag_aliases, param: :name, except: :show
  end

  resources :restaurants do
    resources :restaurant_locations
    resources :restaurant_aliases, param: :name, except: :show
  end 

  resources :users

  root 'tags#index'
  get '' => 'tags#search'
  post '' => 'tags#search'
  get '/tags/:id/tag_aliases/:name' => 'tags#show'
  get '/restaurants/:id/restaurant_aliases/:name' => 'restaurants#show'
  get '/views' => 'view#index'

end

app/controllers/restaurant_aliases_controller.rb
class RestaurantAliasesController < ApplicationController

  respond_to :html

  def index
    @restaurant_aliases = RestaurantAlias.where(restaurant_id: params[:restaurant_id])
    respond_with(@restaurant_aliases)
  end

  def show
    @restaurant_aliases = RestaurantAlias.where(restaurant_id: params[:restaurant_id])

  end

  def new
    @restaurant_alias = RestaurantAlias.new
    respond_with(@restaurant_alias)
  end

  def edit
  end

  def create
    @restaurant_alias = RestaurantAlias.new(restaurant_alias_params)
    @restaurant_alias.save
    respond_with(@restaurant_alias.restaurant)
  end

  def update
    @restaurant_alias.update(restaurant_alias_params)
    respond_with(@restaurant_alias)
  end

  def destroy
    @restaurant_alias = RestaurantAlias.where(restaurant_id: params[:restaurant_id], name: params[:name]).first
    @restaurant = @restaurant_alias.restaurant
    if @restaurant_alias.destroy
     redirect_to @restaurant
    end
  end

  private
    def set_restaurant_alias
      @restaurant_alias = RestaurantAlias.find(params[:id])
    end

    def restaurant_alias_params
      params.require(:restaurant_alias).permit(:name, :restaurant_id)
    end
end

app/helpers/restaurant_aliases_helper.rb
module RestaurantAliasesHelper
end

app/views/restaurant_aliases/_form.html.erb
<%= simple_form_for [@restaurant, @restaurant_alias], url: restaurant_restaurant_aliases_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :restaurant %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurant_aliases/edit.html.erb
<h1>Editing restaurant_alias</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_alias %> |
<%= link_to 'Back', restaurant_aliases_path %>

app/views/restaurant_aliases/index.html.erb
<h1>Listing restaurant_aliases</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant_aliases.each do |restaurant_alias| %>
      <tr>
        <td><%= restaurant_alias.name %></td>
        <td><%= restaurant_alias.restaurant %></td>
        <td><%= link_to 'Show', restaurant_restaurant_aliases_path %></td>
        <td><%= link_to 'Destroy', [restaurant_alias.restaurant, restaurant_alias], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant alias', new_restaurant_restaurant_alias_path %>

app/views/restaurant_aliases/new.html.erb
<h1>New restaurant_alias</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_restaurant_aliases_path %>

app/views/restaurant_aliases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant_alias.name %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @restaurant_alias.restaurant %>
</p>

<%= link_to 'Edit', edit_restaurant_alias_path(@restaurant_alias) %> |
<%= link_to 'Back', restaurant_aliases_path %>